### ISSUE TITLE
Toolbar shows only one folder after restart

### ISSUE THREAD

**Issue by ghost** [andreicristianpetcu/autohide_after_newtab#1]
Hello, the hiding functionality works well on the first firefox session after implementing your css in the userChrome file, but after a restart it only shows the first folder (of my four toolbar folders) ... i don't know any css so i'm not sure if it only requires a bit of tweaking or what ...

could you try adding a couple folders to your toolbar to see if you have the same issue ...

i'm on firefox 57 beta by the way... i don't think it has to do with my not being on nightly?

**Comment by cteenis** [comment]
Same issue here. I am using 57.0 (64-bit). However, it became normal after I hide and then show the bookmark toolbar. This only works on the current window, not new windows, nor after restart. No idea how to permanently fix it.
